# Site settings
title: Dan Brunskill Photography
email: "d.brunskill@gmail.com"
description: "Photo Journal"
url: "https://danbrunskill.github.io"
baseurl: ""
facebook_username: ""
twitter_username: "@danbrunskill_"
instagram_username: "@danielbrunskill"
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   photorama
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : false
  disqus :
    short_name : ""

# Internal nav
nav:
  - Bark in the Park: "https://danbrunskill.github.io/barkinthepark/"  
  - WEC Betel: "https://danbrunskill.github.io/betel/"
  - Portraits: "https://danbrunskill.github.io/portraits/"
  - Bark in the Pool: "https://danbrunskill.github.io/barkinthepool/"
  - Burning Man Dance : "https://danbrunskill.github.io/burningman/"
  - Ice Cube : "https://danbrunskill.github.io/icecube/"
  
  
 
  
  

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
